apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: ia-courses
type: Opaque
stringData:
  jwt-secret: "local-dev-jwt-secret-2024"
  postgres-user: "administrador"
  postgres-password: "secure_password_123"
  postgres-db: "ia_courses_db"
